language: java
sudo: false
matrix:
  include:
    - jdk: openjdk7
      env: TEST_GRADLE_VERSIONS=2.14
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.5
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.6
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.7
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.8
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.9
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.10
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.11
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.12
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.13
    - jdk: oraclejdk8
      env: TEST_GRADLE_VERSIONS=2.14
install: true
script: ./gradlew build -Ptest.gradle-versions="$TEST_GRADLE_VERSIONS"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native/
    - $HOME/.gradle/daemon/native/
